from configs import game_config


SCR_SIZE = SCR_WIDTH, SCR_HEIGHT = 1920, 1000

CAMERA_START_POS = 0, 0
CAMERA_SPEED = 30

SELECTED_SIZE = SELECTED_WIDTH, SELECTED_HEIGHT = 200, 200
SELECTED_TO_COMMAND_INDENT = 100

COMMAND_SIZE = COMMAND_WIDTH, COMMAND_HEIGHT = 90, 70
COMMANDS_INDENT = 130

MINIMAP_WIDTH = 400
MINIMAP_HEIGHT = int(MINIMAP_WIDTH * game_config.MAP_HEIGHT / game_config.MAP_WIDTH)
MINIMAP_SIZE = MINIMAP_WIDTH, MINIMAP_HEIGHT

MINIMAP_FRAME_WIDTH = int(MINIMAP_WIDTH * SCR_WIDTH / game_config.MAP_WIDTH)
MINIMAP_FRAME_HEIGHT = int(MINIMAP_HEIGHT * SCR_HEIGHT / game_config.MAP_HEIGHT)
MINIMAP_FRAME_SIZE = MINIMAP_FRAME_WIDTH, MINIMAP_FRAME_HEIGHT

BORDERS_COLOR = (166, 166, 166)
BORDERS_SIZE = 2
